### ISSUE TITLE
Headings as span elements

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#208]
We have a use case whereby we need to use the styling of a heading however, semantically it does not make sense as a `h2`.

We propose that we add span to the as type under `IStyledHeadingProps`. 

https://github.com/zopaUK/react-components/blob/9ef3191c343e28b61ae0393b096c6bf22fb4f9f6/src/components/atoms/Heading/Heading.tsx#L15

![Screenshot 2020-02-07 at 10 31 09](https://user-images.githubusercontent.com/3974301/74022237-028d7080-4995-11ea-8dad-0eed58f2f49b.png)

**Comment by lluia** [comment]
To me this could work 👍🏻  

One of the challenges we'll hit though is that currently, the **tag defines the size**:

https://github.com/zopaUK/react-components/blob/master/src/components/atoms/Heading/Heading.tsx#L29

So when telling it to render a `span`, you'll need an extra prop to specify which size you want:
```jsx
<Heading as="span" size="h2">Foo</h2>
```

**Comment by moshie** [comment]
Might be a good idea to separate concerns?
`<Heading as="span" size="h2">Span Heading styled as a h2</Heading>`
But still have the ability to do:
`<Heading as="h2">Heading styled as a h2</Heading>`
So it doesn't break the api?

WDYT?

**Comment by thegrinder** [comment]
I think we could just map the font size to `size` prop instead of `as` and let the `as` prop behave the same way as it does in any `styled` component. That would be a breaking change but there is already `v3` branch that you can create a PR against. Also, one thing to keep in mind is that if you use it as span, it will be `display: inline` by default which is different than headings which is `display: block`. So we would have to throw in an extra rule so that the behavior is consistent regardless of what element you use

**Comment by moshie** [comment]
> That would be a breaking change

How come? Couldn't we implement some logic to set the size based on the as prop in the event the size prop was not passed?

Happy to implement a PR to demo?

> if you use it as span, it will be display: inline by default

Good point, I think consistency is key and the span should be `display: block;` similar to h1-6

**Comment by thegrinder** [comment]
When I said it would be a braking change, I was referring to my proposed solution which means using required `size` prop instead of `as`. This way we wouldn't have to assign a default font size when the heading is `span`. On the other hand, what you're suggesting forces us to do so but you're right, it doesn't introduce any breaking changes. Not sure which would be better...

**Comment by thegrinder** [comment]
When I said it would be a braking change, I was referring to my proposed solution which means using required `size` prop instead of `as`. This way we wouldn't have to assign a default font size when the heading is `span`. On the other hand, what you're suggesting forces us to do so but you're right, it doesn't introduce any breaking changes. Not sure which would be better...

**Comment by lluia** [comment]
Happy we both paths, so whoever picks that up can choose which? 
( _whether with breaking change or not_ )

I want to [finish v3](https://github.com/zopaUK/react-components/milestone/2) end of next week, so squeezing there is no problem 👍🏻

**Comment by lluia** [comment]
Addressed ☝🏻 👀
