### ISSUE TITLE
Implement some alias system for imports

### ISSUE THREAD

**Issue by dfvalero** [zopaUK/react-components#508]
The project is growing, and we need to think about a way to clean our imports. Example:

![Screenshot 2020-06-16 at 11 45 12](https://user-images.githubusercontent.com/337955/84759375-ef378500-afc6-11ea-9d0e-be66f0ee9479.png)

Any ideas?

**Comment by poteirard** [comment]
My planing to add a `baseUrl` in tsconfig to be able to do:`constants` and `helpers/responsiveness`. But I was planing to do this after the bank launch

**Comment by dfvalero** [comment]
> My plan was to add a `baseUrl` in tsconfig to be able to do:`constants` and `helpers/responsiveness`. But I was planing to do this after the bank launch

I think that we need to think about a proper alias system for all the imports, not only constants and responsiveness, Example:

![Screenshot 2020-06-16 at 12 03 20](https://user-images.githubusercontent.com/337955/84761250-7980e880-afc9-11ea-81e2-9886df49f9cf.png)

**Comment by thegrinder** [comment]
I guess removing molecules/atoms/organisms division would alleviate some the pain 😅

**Comment by poteirard** [comment]
@dfvalero that would work for all the imports not only those 2

**Comment by poteirard** [comment]
I've tried just by using `baseUrl` and it happened what I thought it could happen. There's already a package called "constants" so it complains. So `baseUrl` is not an option. To fix this there's another possibility, use `paths` alias in TS, which is a pain in the ass because:
1. Jest config needs the `moduleMapper` configuration
2. webpack needs the aliases
3. Rollup also aliases

Ofc it can be done, but I wonder if it's necessary given the rabbit hole of tooling config? Does anyone read the imports anyway?

One thing I would do is what @thegrinder suggested: getting rid of on the level of the paths (atoms, molecules, etc...). But this is a big change for some apps so I would do this in the near future (after bank launch)

**Comment by dfvalero** [comment]
Idea:

https://mobile.twitter.com/mkldny/status/1253123287711985664
